<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2018-02-14 20:29:04',
                'updated_at' => '2018-02-14 20:29:04',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2018-02-14 20:29:04',
                'updated_at' => '2018-02-27 06:53:08',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2018-02-14 20:29:04',
                'updated_at' => '2018-02-27 06:53:08',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2018-02-14 20:29:04',
                'updated_at' => '2018-02-27 06:53:08',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2018-02-14 20:29:04',
                'updated_at' => '2018-02-27 06:53:08',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 1,
                'created_at' => '2018-02-14 20:29:04',
                'updated_at' => '2018-02-15 01:00:49',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 2,
                'created_at' => '2018-02-14 20:29:04',
                'updated_at' => '2018-02-15 01:00:49',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 3,
                'created_at' => '2018-02-14 20:29:04',
                'updated_at' => '2018-02-15 01:00:49',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2018-02-14 20:29:04',
                'updated_at' => '2018-02-27 06:53:08',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Skills',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2018-02-15 01:01:22',
                'updated_at' => '2018-02-27 06:53:08',
                'route' => NULL,
                'parameters' => '',
            ),
            10 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '/admin/category-skills',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 13,
                'order' => 1,
                'created_at' => '2018-02-15 01:03:36',
                'updated_at' => '2018-02-15 01:37:27',
                'route' => NULL,
                'parameters' => '',
            ),
            11 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Skills',
                'url' => '/admin/skills',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 13,
                'order' => 2,
                'created_at' => '2018-02-15 01:07:27',
                'updated_at' => '2018-02-15 01:07:36',
                'route' => NULL,
                'parameters' => '',
            ),
            12 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Details',
                'url' => '/admin/skill-details',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 13,
                'order' => 3,
                'created_at' => '2018-02-15 01:32:57',
                'updated_at' => '2018-02-15 01:37:37',
                'route' => NULL,
                'parameters' => '',
            ),
            13 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Portfolio',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2018-02-15 01:35:08',
                'updated_at' => '2018-02-15 01:56:01',
                'route' => NULL,
                'parameters' => '',
            ),
            14 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => 'admin/category-portfolios',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 17,
                'order' => 1,
                'created_at' => '2018-02-15 01:36:20',
                'updated_at' => '2018-02-15 01:36:31',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Portfolio',
                'url' => 'admin/portfolios',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 17,
                'order' => 2,
                'created_at' => '2018-02-15 01:36:45',
                'updated_at' => '2018-02-27 06:50:55',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Files',
                'url' => 'admin/portfolio-files',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 17,
                'order' => 4,
                'created_at' => '2018-02-15 01:37:15',
                'updated_at' => '2018-02-27 06:53:08',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Biography',
                'url' => 'admin/biography',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2018-02-15 01:39:10',
                'updated_at' => '2018-02-27 06:53:08',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Items',
                'url' => 'admin/portfolio-items',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 17,
                'order' => 3,
                'created_at' => '2018-02-27 06:52:57',
                'updated_at' => '2018-02-27 07:54:08',
                'route' => NULL,
                'parameters' => '',
            ),
        ));
        
        
    }
}