<?php

use Illuminate\Database\Seeder;

class PortfolioFilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('portfolio_files')->delete();

        \DB::table('portfolio_files')->insert(array (
            0 =>
            array (
                'id' => 1,
                'portfolio_item_id' => 1,
                'image' => 'portfolio-files/cg-movie/files/ctyrlistek-ve-sluzbach-krale-cihelna-exterier.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-02-27 00:00:00',
            ),
            1 =>
            array (
                'id' => 2,
                'portfolio_item_id' => 1,
                'image' => 'portfolio-files/cg-movie/files/ctyrlistek-ve-sluzbach-krale-cihelna-interier.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-02-27 00:00:00',
            ),
            2 =>
            array (
                'id' => 3,
                'portfolio_item_id' => 1,
                'image' => 'portfolio-files/cg-movie/files/ctyrlistek-ve-sluzbach-krale-background-1.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-02-27 00:00:00',
            ),
            3 =>
            array (
                'id' => 4,
                'portfolio_item_id' => 1,
                'image' => 'portfolio-files/cg-movie/files/ctyrlistek-ve-sluzbach-krale-background-2.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-02-27 00:00:00',
            ),
            4 =>
            array (
                'id' => 5,
                'portfolio_item_id' => 17,
                'image' => 'portfolio-files/high-poly/redbull-plane/redbull-plane.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-02 15:44:01',
            ),
            5 =>
            array (
                'id' => 6,
                'portfolio_item_id' => 2,
                'image' => 'portfolio-files/low-poly/yacht/yacht-front.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-02-27 00:00:00',
            ),
            6 =>
            array (
                'id' => 7,
                'portfolio_item_id' => 5,
                'image' => 'portfolio-files/realtime-visualization/crib/crib-2.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'portfolio_item_id' => 5,
                'image' => 'portfolio-files/realtime-visualization/crib/crib-3.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'portfolio_item_id' => 5,
                'image' => 'portfolio-files/realtime-visualization/crib/crib-5.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'portfolio_item_id' => 4,
                'image' => 'portfolio-files/realtime-visualization/vila-lignum/vila-lignum-1.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'portfolio_item_id' => 4,
                'image' => 'portfolio-files/realtime-visualization/vila-lignum/vila-lignum-3.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'portfolio_item_id' => 4,
                'image' => 'portfolio-files/realtime-visualization/vila-lignum/vila-lignum-4.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'portfolio_item_id' => 4,
                'image' => 'portfolio-files/realtime-visualization/vila-lignum/vila-lignum-5.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'portfolio_item_id' => 3,
                'image' => 'portfolio-files/realtime-visualization/gallery/gallery-exterior-1.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'portfolio_item_id' => 3,
                'image' => 'portfolio-files/realtime-visualization/gallery/gallery-interior-1.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'portfolio_item_id' => 3,
                'image' => 'portfolio-files/realtime-visualization/gallery/gallery-interior-of-cafe-1.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'portfolio_item_id' => 9,
                'image' => 'portfolio-files/games/dayz/ship-wreck-3.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 07:01:37',
            ),
            17 =>
            array (
                'id' => 18,
                'portfolio_item_id' => 9,
                'image' => 'portfolio-files/games/dayz/ship-wreck-1.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 07:01:45',
            ),
            18 =>
            array (
                'id' => 19,
                'portfolio_item_id' => 9,
                'image' => 'portfolio-files/games/dayz/ship-wreck-2.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 07:01:50',
            ),
            19 =>
            array (
                'id' => 20,
                'portfolio_item_id' => 9,
                'image' => 'portfolio-files/games/dayz/apartment-building-exterior.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 07:01:58',
            ),
            20 =>
            array (
                'id' => 21,
                'portfolio_item_id' => 9,
                'image' => 'portfolio-files/games/dayz/apartment-building-interior.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 07:02:04',
            ),
            21 =>
            array (
                'id' => 22,
                'portfolio_item_id' => 8,
                'image' => 'portfolio-files/games/take-on/space-needle-01.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 07:00:51',
            ),
            22 =>
            array (
                'id' => 23,
                'portfolio_item_id' => 8,
                'image' => 'portfolio-files/games/take-on/space-needle-02.jpg',
                'url' => NULL,
                'title' => 'VIDEO PLACEHOPLDER',
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 07:00:59',
            ),
            23 =>
            array (
                'id' => 24,
                'portfolio_item_id' => 8,
                'image' => 'portfolio-files/games/take-on/takeon-cover.png',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 07:01:06',
            ),
            24 =>
            array (
                'id' => 25,
                'portfolio_item_id' => 6,
                'image' => 'portfolio-files/games/mafia-II/uptown-flat-1.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'portfolio_item_id' => 6,
                'image' => 'portfolio-files/games/mafia-II/uptown-flat-2.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'portfolio_item_id' => 6,
                'image' => 'portfolio-files/games/mafia-II/uptown-flat-3.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'portfolio_item_id' => 7,
                'image' => 'portfolio-files/games/mafia-II/balls-&-beans-1.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:06:27',
            ),
            28 =>
            array (
                'id' => 29,
                'portfolio_item_id' => 6,
                'image' => 'portfolio-files/games/mafia-II/cossack-car.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'portfolio_item_id' => 7,
                'image' => 'portfolio-files/games/mafia-II/balls-&-beans-2.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:06:39',
            ),
            30 =>
            array (
                'id' => 31,
                'portfolio_item_id' => 7,
                'image' => 'portfolio-files/games/mafia-II/greenfield-flat.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:06:51',
            ),
            31 =>
            array (
                'id' => 32,
                'portfolio_item_id' => 10,
                'image' => 'portfolio-files/3d-print/files/3D-print-1.gif',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 07:00:44',
            ),
            32 =>
            array (
                'id' => 33,
                'portfolio_item_id' => 10,
                'image' => 'portfolio-files/3d-print/files/3D-print-2.gif',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:57:44',
            ),
            33 =>
            array (
                'id' => 34,
                'portfolio_item_id' => 10,
                'image' => 'portfolio-files/3d-print/files/3D-print-4.gif',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:57:49',
            ),
            34 =>
            array (
                'id' => 35,
                'portfolio_item_id' => 10,
                'image' => 'portfolio-files/3d-print/files/3D-print-3.gif',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:57:54',
            ),
            35 =>
            array (
                'id' => 36,
                'portfolio_item_id' => 14,
                'image' => 'portfolio-files/rendering/mpio/mpio-player.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:59:50',
            ),
            36 =>
            array (
                'id' => 37,
                'portfolio_item_id' => 15,
                'image' => 'portfolio-files/rendering/shelves/visualization-of-shelves-1.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:55:31',
            ),
            37 =>
            array (
                'id' => 38,
                'portfolio_item_id' => 15,
                'image' => 'portfolio-files/rendering/shelves/visualization-of-shelves-2.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:55:26',
            ),
            38 =>
            array (
                'id' => 39,
                'portfolio_item_id' => 13,
                'image' => 'portfolio-files/rendering/zemeklon/zemeklon.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:55:21',
            ),
            39 =>
            array (
                'id' => 40,
                'portfolio_item_id' => 12,
                'image' => 'portfolio-files/rendering/alfa-romeo/alfa-romeo-c8-spider-1.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:54:42',
            ),
            40 =>
            array (
                'id' => 41,
                'portfolio_item_id' => 12,
                'image' => 'portfolio-files/rendering/alfa-romeo/alfa-romeo-c8-spider-2.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:54:47',
            ),
            41 =>
            array (
                'id' => 42,
                'portfolio_item_id' => 12,
                'image' => 'portfolio-files/rendering/alfa-romeo/alfa-romeo-c8-spider-3.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:54:52',
            ),
            42 =>
            array (
                'id' => 43,
                'portfolio_item_id' => 10,
                'image' => 'portfolio-files/3d-print/files/all_characters_poster.jpg',
                'url' => NULL,
                'title' => 'All characters placeholder',
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:59:06',
            ),
            43 =>
            array (
                'id' => 44,
                'portfolio_item_id' => 11,
                'image' => 'portfolio-files/3d-print/files/animation.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:58:29',
            ),
            44 =>
            array (
                'id' => 45,
                'portfolio_item_id' => 11,
                'image' => 'portfolio-files/3d-print/files/piskoviste_poster.jpg',
                'url' => NULL,
                'title' => 'krmitko_poster.jpg',
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-28 07:54:00',
                'updated_at' => '2018-03-05 06:58:17',
            ),
            45 =>
            array (
                'id' => 46,
                'portfolio_item_id' => 11,
                'image' => 'portfolio-files/3d-print/files/krmitko_poster.jpg',
                'url' => 'eSL3idbdQ7Y',
                'title' => 'video',
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => '2018-03-05 06:59:21',
            ),
            46 =>
            array (
                'id' => 47,
                'portfolio_item_id' => 1,
                'image' => 'portfolio-files/cg-movie/files/ctyrlistek-ve-sluzbach-krale-characters.jpg',
                'url' => NULL,
                'title' => NULL,
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-02-27 00:00:00',
                'updated_at' => NULL,
            ),
            47 =>
            array (
                'id' => 48,
                'portfolio_item_id' => 2,
                'image' => 'portfolio-files/low-poly/yacht/yacht-back.jpg',
                'url' => NULL,
                'title' => 'Yacht back',
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-03-04 20:38:00',
                'updated_at' => '2018-03-04 20:39:06',
            ),
            48 =>
            array (
                'id' => 49,
                'portfolio_item_id' => 16,
                'image' => 'portfolio-files/high-poly/ferrari/ferrari-front.jpg',
                'url' => NULL,
                'title' => 'ferrari-front',
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-03-04 20:48:25',
                'updated_at' => '2018-03-04 20:48:25',
            ),
            49 =>
            array (
                'id' => 50,
                'portfolio_item_id' => 16,
                'image' => 'portfolio-files/high-poly/ferrari/ferrari-back.jpg',
                'url' => NULL,
                'title' => 'ferrari back',
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-03-04 20:48:47',
                'updated_at' => '2018-03-04 20:48:47',
            ),
            50 =>
            array (
                'id' => 51,
                'portfolio_item_id' => 18,
                'image' => 'portfolio-files/low-poly/porsche/porsche-front.jpg',
                'url' => NULL,
                'title' => 'porsche-front',
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-03-04 20:55:00',
                'updated_at' => '2018-03-04 20:55:57',
            ),
            51 =>
            array (
                'id' => 52,
                'portfolio_item_id' => 18,
                'image' => 'portfolio-files/low-poly/porsche/porsche-back.jpg',
                'url' => NULL,
                'title' => 'porsche-back',
                'author' => NULL,
                'summary' => NULL,
                'description' => NULL,
                'created_at' => '2018-03-04 20:55:00',
                'updated_at' => '2018-03-04 20:56:03',
            ),
        ));


    }
}